### ISSUE TITLE
Allow @username in Twitter handles

### ISSUE THREAD

**Issue by msgilligan** [marchof/javabubble#135]
It is common (and supported by Github) to prefix Twitter handles with an `@`.  I absent-mindedly copied my Twitter handle into my Github handle in `javapeople.yaml` and my PR failed. It was easy enough to fix, but others may make the same mistake.

**Comment by marchof** [comment]
We need to agree on a format. Otherwise links on http://javabubble.org/ will break.

**Comment by msgilligan** [comment]
I was thinking the `java people.yaml' file should accept Github names with and without the `@` and add/remove it when processing/converting, but maybe that is too much of a hassle or maybe you are using the `.yaml` file directly.

Maybe I'm the only one that's going to get hit by this. It's not a big issue, feel free to close it. I just thought I should at least make you aware of how I got bitten.

**Comment by marchof** [comment]
I seriously don't know who is using the yaml file. Its like a open data project. I prefer to stick with a strict format.

Don't worry, you're not the first one to require multiple steps to fix yaml syntax, sorting, etc 😅

That's why we have a CI build which provides instant feedback and everyone was able to fix it so far. Kind of entry test for this list 😜
